import { z } from 'zod';
import { journeyStateSchema, moneySchema } from '@ai-concierge/domain';

/**
 * Customer web chat (docs/MASTER-PLAN.md Phase 5 "Web chat" + Phase 8 "Chat
 * with AI"). A customer is identified only by a random session id their
 * browser generated — an unguessable bearer secret, never a login. Everything
 * here is safe to show the customer: no internal ids beyond their own
 * conversation, no integrity hashes, no staff identities.
 */
export const chatSessionIdSchema = z.string().uuid();

export const chatRoleSchema = z.enum(['CUSTOMER', 'CONCIERGE', 'STAFF']);
export type ChatRole = z.infer<typeof chatRoleSchema>;

/** A car photo shown inline in the chat — the customer asked to see the car. */
export const chatAttachmentSchema = z.object({
  type: z.literal('image'),
  url: z.string().url(),
  caption: z.string(),
});
export type ChatAttachment = z.infer<typeof chatAttachmentSchema>;

export const chatMessageSchema = z.object({
  id: z.string().uuid(),
  role: chatRoleSchema,
  content: z.string(),
  attachments: z.array(chatAttachmentSchema).default([]),
  createdAt: z.string().datetime(),
});
export type ChatMessage = z.infer<typeof chatMessageSchema>;

/** The customer-facing view of a quote: every price line, but nothing internal. */
export const chatQuoteSchema = z.object({
  quoteId: z.string().uuid(),
  status: z.enum(['ISSUED', 'PENDING_REVIEW']),
  currency: z.string().length(3),
  lineItems: z.array(
    z.object({
      description: z.string(),
      quantity: z.number().int().positive(),
      unitAmount: moneySchema,
      amount: moneySchema,
    }),
  ),
  taxes: z.array(z.object({ description: z.string(), amount: moneySchema })),
  fees: z.array(z.object({ description: z.string(), amount: moneySchema })),
  discounts: z.array(z.object({ description: z.string(), amount: moneySchema })),
  deposit: moneySchema,
  total: moneySchema,
  validUntil: z.string().datetime(),
});
export type ChatQuote = z.infer<typeof chatQuoteSchema>;

/** What the concierge currently knows about the requested rental. */
export const chatBookingSchema = z.object({
  vehicle: z.string().nullable(),
  pickupDate: z.string().datetime().nullable(),
  returnDate: z.string().datetime().nullable(),
  pickupLocation: z.string().nullable(),
});
export type ChatBooking = z.infer<typeof chatBookingSchema>;

export const sendChatMessageBodySchema = z
  .object({
    sessionId: chatSessionIdSchema,
    /** Generated by the browser per message so a double-tap or retry is never processed twice. */
    clientMessageId: z.string().uuid(),
    message: z.string().trim().min(1).max(1000),
  })
  .strict();
export type SendChatMessageBody = z.infer<typeof sendChatMessageBodySchema>;

export const chatStateSchema = z.object({
  conversationId: z.string().uuid().nullable(),
  journeyState: journeyStateSchema.nullable(),
  /** A person has taken over: the concierge will only acknowledge until they reply. */
  escalated: z.boolean(),
  booking: chatBookingSchema.nullable(),
  quote: chatQuoteSchema.nullable(),
});
export type ChatState = z.infer<typeof chatStateSchema>;

export const sendChatMessageResponseSchema = chatStateSchema.extend({
  reply: z.object({
    id: z.string().uuid().nullable(),
    text: z.string(),
    /** AI_GENERATED when Gemini worded it, otherwise TEMPLATE (the deterministic draft). */
    source: z.enum(['AI_GENERATED', 'TEMPLATE']),
    /** Car photos to show with this reply (only when the customer asked to see a car). */
    attachments: z.array(chatAttachmentSchema).default([]),
    createdAt: z.string().datetime(),
  }),
});
export type SendChatMessageResponse = z.infer<typeof sendChatMessageResponseSchema>;

export const getChatSessionParamsSchema = z.object({ sessionId: chatSessionIdSchema });
export type GetChatSessionParams = z.infer<typeof getChatSessionParamsSchema>;

export const getChatSessionResponseSchema = chatStateSchema.extend({
  messages: z.array(chatMessageSchema),
});
export type GetChatSessionResponse = z.infer<typeof getChatSessionResponseSchema>;
